<a href="https://colab.research.google.com/github/PoongGu/test_project/blob/main/lesson_03_numpy_3_modules_statistics%2C_lin%2Clogspace%2C_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy modules

In [21]:
import numpy as np

ary = [26, 28, 30, 35, 27, 31, 44]
ary = np.array(ary)
ary

array([26, 28, 30, 35, 27, 31, 44])

In [22]:
arr = np.random.randn(100)
arr

array([-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39649634,
       -1.44411381, -0.50446586,  0.16003707,  0.87616892,  0.31563495,
       -2.02220122, -0.30620401,  0.82797464,  0.23009474,  0.76201118,
       -0.22232814, -0.20075807,  0.18656139,  0.41005165,  0.19829972,
        0.11900865, -0.67066229,  0.37756379,  0.12182127,  1.12

#### Statistics modules
    - max, min, median, mean, std, var
    - cov, corrcoef

In [23]:
np.max(arr), np.min(arr), np.mean(arr), np.var(arr), np.std(arr)

(2.1855754065331614,
 -2.022201215824003,
 0.06970549447305932,
 0.679775397885683,
 0.8244849288408388)

#### linspace, logspace
    - linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
    - logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [24]:
np.linspace(0, 100,5 )

array([  0.,  25.,  50.,  75., 100.])

##### logspace
    - log10(x1)=2, log_10(x_2)=4

In [25]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

##### 2000년 최저시급과 2019년 최저시급을 가정하여 선형적 증가 추세를 보고싶다면?

In [26]:
time_00 = 1600
time_19 = 8350
np.linspace(time_00, time_19, 10)

array([1600., 2350., 3100., 3850., 4600., 5350., 6100., 6850., 7600.,
       8350.])

#### numpy random module
    - seed : 랜덤의 설정값
    - rand : 균등분포로 난수 생생
    - randn : 정규분포로 난수 생성
    - randint : 균등분포로 정수 생성
    - shuffle : 섞기
    - choice : 데이터를 특정 확률로 뽑기

##### seed

In [27]:
np.random.seed(1) # arbitrary
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

##### rand

In [28]:
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [29]:
np.random.randn(10)

array([ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

In [30]:
np.random.rand(10)

array([0.69187711, 0.31551563, 0.68650093, 0.83462567, 0.01828828,
       0.75014431, 0.98886109, 0.74816565, 0.28044399, 0.78927933])

##### randn

In [31]:
np.random.randn(10)

array([-0.12289023, -0.93576943, -0.26788808,  0.53035547, -0.69166075,
       -0.39675353, -0.6871727 , -0.84520564, -0.67124613, -0.0126646 ])

##### randint

In [32]:
x = np.random.randint(1, 10, (4, 4))
x

array([[8, 4, 1, 9],
       [8, 8, 2, 2],
       [4, 1, 9, 7],
       [5, 6, 7, 3]])

In [33]:
np.random.shuffle(x)
x

array([[5, 6, 7, 3],
       [4, 1, 9, 7],
       [8, 8, 2, 2],
       [8, 4, 1, 9]])

In [35]:
arr = np.random.randint(0, 10, (3,3))
arr

array([[7, 8, 4],
       [4, 7, 7],
       [4, 9, 0]])

In [47]:
#np.any(arr > 5)

# np.all(arr > 5)

# np.all(arr < 10)

# np.argmin(arr, axis=0)

# np.argmax(arr, 1)

# np.argsort(arr, axis=0)

# arr[np.where(arr>5)]

np.where(arr<5, 10, arr)

array([[ 7,  8, 10],
       [10,  7,  7],
       [10,  9, 10]])

In [48]:
arr = np.random.randint(0, 10, (4,4))
arr

array([[2, 0, 7, 1],
       [7, 9, 8, 4],
       [0, 1, 9, 8],
       [2, 3, 1, 2]])

In [50]:
# np.max(arr, axis=1)

np.mean(arr , 0)

array([2.75, 3.25, 6.25, 3.75])

In [52]:
arr = np.random.randint(0, 10, (2,4))
arr

array([[2, 7, 7, 0],
       [6, 5, 1, 4]])

In [57]:
arr1 = arr[..., np.newaxis]
arr1.shape

arr2 = np.squeeze(arr1, -1)
arr2.shape

arr3 = np.transpose(arr1, (2,1,0))
arr3.shape, arr1.shape

arr4 = arr1.reshape(1,4,2)

arr5 = arr2.T
arr5.shape

(4, 2)