<a href="https://colab.research.google.com/github/PoongGu/test_project/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr = np.array([1,2,3], dtype='int32')
type(arr), arr

(numpy.ndarray, array([1, 2, 3], dtype=int32))

In [7]:
arr2 = np.array([[1,2,3,],
                 [4,5,6]])
print(arr2) # 행렬 확인 
print(arr2.ndim) # 행렬의 차원
print(arr2.shape) # 행렬의 형태
print(arr2.size) # 행렬 내 원소개수
print(arr2.dtype) # 행렬의 자료형

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [8]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [9]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [10]:
a = np.random.randint(2, 10, size=(5,))
b = np.random.randint(2, 10, size=(2,4))
c = np.random.randint(2, 10, size=(2,3,4))
print(a)
print(b)
print(c)


[4 6 5 4 6]
[[9 6 2 9]
 [4 6 5 2]]
[[[9 2 8 6]
  [9 2 6 4]
  [5 7 7 8]]

 [[7 3 4 2]
  [4 5 3 8]
  [6 4 7 6]]]


In [12]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr2[1]

array([4, 5, 6])

In [15]:
arr2[1, 1]

5

In [16]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [17]:
arr3 = np.array([[1,2,3],
                 [0,1,0]])
arr3[1][1] = 0
arr3

array([[1, 2, 3],
       [0, 0, 0]])

## array 조건 선택

In [18]:
arr3[0] = 5
arr3[1] = [5,6,7]
arr3

array([[5, 5, 5],
       [5, 6, 7]])

In [19]:
idx = arr3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [20]:
arr3[idx]

array([6, 7])

# 조건에 맞는 값만 변경

In [21]:
arr3[idx] = 100
arr3

array([[  5,   5,   5],
       [  5, 100, 100]])

# zero array

In [22]:
zero_arr = np.zeros(shape=(2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
type(zero_arr)

numpy.ndarray

In [24]:
zero_arr.dtype # 실수형 값만 바꿔 넣을 수 있음

dtype('float64')

# array안의 데이터 형태 변경

In [25]:
z2 = zero_arr.astype('int16')
z2.dtype

dtype('int16')

# one array

In [26]:
one_arr = np.ones((2,3))
one_arr.dtype, one_arr

(dtype('float64'), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [27]:
one_arr2 = np.ones((2,3,2)).astype('int')
one_arr2.dtype, one_arr2

(dtype('int64'), array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [29]:
id = np.identity(n=5, dtype=np.int8) # 단위 행렬
id

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

# 범위값 array 생성

In [31]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])